# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=400)),
                ('movie_poster', models.CharField(max_length=1000)),
                ('genre', models.CharField(max_length=400)),
                ('director', models.CharField(max_length=400)),
                ('starring', models.CharField(max_length=500)),
                ('summary', models.CharField(default='', max_length=2000)),
                ('release_date', models.IntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.MovieInfo'),
        ),
    ]
