# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='movieinfo',
            name='summary',
        ),
    ]
