# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20170503_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='year',
            field=models.IntegerField(default=1900),
        ),
    ]
